version: '3.8'

services:
  sentiment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment-analysis-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/final_model
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount model directory (if training separately)
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - sentiment-network

networks:
  sentiment-network:
    driver: bridge
